SampleApp1.Web.MVC/Controllers/ArtistsController.cs
using Microsoft.AspNetCore.Mvc;

namespace SampleApp1.Web.MVC.Controllers
{
    [Route("artists")]
    public class ArtistsController : Controller
    {
        [HttpGet("details")]
        public IActionResult Details(Guid id)
        {
            return this.Ok(id);
        }
    }
}

SampleApp1.Web.MVC/Controllers/GenresController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using SampleApp1.Core.Interfaces.Services;
using SampleApp1.Data.Models;
using SampleApp1.Web.ViewModels.Genres;

namespace SampleApp1.Web.MVC.Controllers
{
    [Route("genres")]
    public class GenresController : Controller
    {
        private readonly IGenreService _genreService;
        private readonly IMapper _mapper;

        public GenresController(IGenreService genreService, IMapper mapper)
        {
            this._genreService = genreService ?? throw new ArgumentNullException(nameof(genreService));
            this._mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }

        [HttpGet]
        public IActionResult Index()
        {
            var genres = this._genreService.GetAll();
            var viewModels = this._mapper.Map<IEnumerable<GenreViewModel>>(genres);

            return this.View(viewModels);
        }

        [HttpGet("create")]
        public IActionResult Create()
        {
            return this.View();
        }

        [HttpPost("create"), ValidateAntiForgeryToken]
        public IActionResult Create([FromForm] GenreCreateModel inputModel)
        {
            if (!ModelState.IsValid) return this.View(inputModel);

            var genre = this._mapper.Map<Genre>(inputModel);
            this._genreService.Create(genre);

            return this.RedirectToAction(nameof(Index));
        }

        [HttpGet("delete")]
        public IActionResult Delete(Guid id)
        {
            var genre = this._genreService.GetOneMinified(id);
            if (genre is null) return this.NotFound();

            var viewModel = this._mapper.Map<GenreMinifiedViewModel>(genre);
            return this.View(viewModel);
        }

        [HttpPost("delete"), ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            this._genreService.Delete(id);
            return this.RedirectToAction(nameof(Index));
        }

        [HttpGet("details")]
        public IActionResult Details(Guid id)
        {
            var genre = this._genreService.GetOne(id);
            if (genre is null) return this.NotFound();

            var viewModel = this._mapper.Map<GenreViewModel>(genre);
            return this.View(viewModel);
        }

        [HttpGet("edit")]
        public IActionResult Edit(Guid id)
        {
            var genre = this._genreService.GetOneEdit(id);
            if (genre is null) return this.NotFound();

            var viewModel = this._mapper.Map<GenreEditModel>(genre);
            return View(viewModel);
        }

        [HttpPost("edit"), ValidateAntiForgeryToken]
        public IActionResult Edit(Guid id, GenreEditModel inputModel)
        {
            if (!ModelState.IsValid) return this.View(inputModel);
            if (id != inputModel.Id) return this.NotFound();

            var genre = this._genreService.GetById(id);
            if (genre is null) return this.NotFound();

            this._mapper.Map(inputModel, genre);
            this._genreService.Update(genre);

            return this.RedirectToAction(nameof(Index));
        }
    }
}

SampleApp1.Web.MVC/Controllers/SongsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Org.BouncyCastle.Utilities;
using SampleApp1.Core.Interfaces.Services;
using SampleApp1.Data;
using SampleApp1.Data.Models;
using SampleApp1.Web.ViewModels.Artists;
using SampleApp1.Web.ViewModels.Genres;
using SampleApp1.Web.ViewModels.Songs;

namespace SampleApp1.Web.MVC.Controllers
{
    [Route("songs")]
    public class SongsController : Controller
    {
        private readonly IArtistService _artistService;
        private readonly IGenreService _genreService;
        private readonly ISongService _songService;
        private readonly IMapper _mapper;

        public SongsController(IArtistService artistService, IGenreService genreService, ISongService songService, IMapper mapper)
        {
            this._artistService = artistService ?? throw new ArgumentNullException(nameof(artistService));
            this._genreService = genreService ?? throw new ArgumentNullException(nameof(genreService));
            this._songService = songService ?? throw new ArgumentNullException(nameof(songService));
            this._mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }

        [HttpGet]
        public IActionResult Index()
        {
            var allSongs = this._songService.GetAll();
            var viewModels = this._mapper.Map<IEnumerable<SongViewModel>>(allSongs);

            return this.View(viewModels);
        }

        [HttpGet("create")]
        public IActionResult Create()
        {
            var viewModel = this.PrepareFormViewModel<SongCreateModel>();
            return this.View(viewModel);
        }

        [HttpPost("create"), ValidateAntiForgeryToken]
        public IActionResult Create([FromForm] SongCreateModel inputModel)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = this.PrepareFormViewModel(inputModel);
                return this.View(viewModel);
            }

            var song = new Song();
            this.ApplyChanges(song, inputModel);

            this._songService.Create(song);

            return this.RedirectToAction(nameof(Index));
        }

        [HttpGet("details")]
        public IActionResult Details(Guid id)
        {
            var song = this._songService.GetOne(id);
            if (song is null) return this.NotFound();

            var viewModel = this._mapper.Map<SongViewModel>(song);
            return this.View(viewModel);
        }

        [HttpGet("delete")]
        public IActionResult Delete(Guid id)
        {
            var song = this._songService.GetOneMinified(id);
            if (song is null) return this.NotFound();

            var viewModel = this._mapper.Map<SongMinifiedViewModel>(song);
            return this.View(viewModel);
        }

        [HttpPost("delete"), ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            this._songService.Delete(id);
            return this.RedirectToAction(nameof(Index));
        }

        [HttpGet("edit")]
        public IActionResult Edit(Guid id)
        {
            var song = this._songService.GetOneEdit(id);
            if (song is null) return this.NotFound();

            var editModel = this._mapper.Map<SongEditModel>(song);
            var formViewModel = this.PrepareFormViewModel(editModel);
            return View(formViewModel);
        }

        [HttpPost("edit"), ValidateAntiForgeryToken]
        public IActionResult Edit(SongEditModel inputModel)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = this.PrepareFormViewModel(inputModel);
                return this.View(viewModel);
            }

            var song = this._songService.GetByIdWithNavigations(inputModel.Id, [nameof(Song.Genres)]);
            if (song is null) return this.NotFound();

            this.ApplyChanges(song, inputModel);
            this._songService.Update(song);

            return this.RedirectToAction(nameof(Index));
        }

        private SongFormViewModel<TInputModel> PrepareFormViewModel<TInputModel>(TInputModel? inputModel = default)
        {
            var allArtists = this._artistService.GetAllMinified();
            var allGenres = this._genreService.GetAllMinified();

            return new SongFormViewModel<TInputModel>
            {
                Artists = this._mapper.Map<IEnumerable<ArtistMinifiedViewModel>>(allArtists),
                Genres = this._mapper.Map<IEnumerable<GenreMinifiedViewModel>>(allGenres),
                InputModel = inputModel
            };
        }

        private void ApplyChanges(Song song, SongCreateModel inputModel)
        {
            var artist = this._artistService.GetById(inputModel.Artist);
            if (artist is null) throw new InvalidOperationException("Artist not found");

            var genres = this._genreService.GetByIds(inputModel.Genres).ToList();
            if (genres.Count != inputModel.Genres.Length)
                throw new InvalidOperationException("Some of the genres are not found.");

            this._mapper.Map(inputModel, song);
            song.Artist = artist;
            song.Genres = genres;
        }
    }
}

SampleApp1.Web.MVC/Views/Songs/Create.cshtml
@model SongFormViewModel<SongCreateModel>
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Song</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="InputModel!.Name" class="control-label"></label>
                <input asp-for="InputModel!.Name" class="form-control" />
                <span asp-validation-for="InputModel!.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InputModel!.Artist" class="control-label"></label>
                @* <select asp-for="InputModel!.Artist" asp-items="@Model.Artists.Select(a => new SelectListItem { Value = a.Id.ToString(), Text = a.Nickname })" class="form-control"></select> *@
                <select asp-for="InputModel!.Artist" asp-items="@Model.Artists.ConstructListItems(a => a.Id.ToString(), a => a.Nickname)" class="form-control"></select>
                <span asp-validation-for="InputModel!.Artist" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InputModel!.Genres" class="control-label"></label>
                <select multiple asp-for="InputModel!.Genres" asp-items="@Model.Genres.Select(a => new SelectListItem { Value = a.Id.ToString(), Text = a.Name })" class="form-control"></select>
                <span asp-validation-for="InputModel!.Genres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

SampleApp1.Web.MVC/Views/Songs/Delete.cshtml
@model SongMinifiedViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Song</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="DeleteConfirmed">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SampleApp1.Web.MVC/Views/Songs/Details.cshtml
@model SongViewModel
@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Song</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Artist.Nickname)
        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Artists" asp-action="Details" asp-route-id="@Model.Artist.Id">@Model.Artist.Nickname</a>
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Genres)
        </dt>
        <dd class="col-sm-10">
            @foreach (var genre in Model.Genres)
            {
                <a asp-controller="Genres" asp-action="Details" asp-route-id="@genre.Id">@genre.Name</a>
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SampleApp1.Web.MVC/Views/Songs/Edit.cshtml
@model SongFormViewModel<SongEditModel>

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Song</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="InputModel!.Id" />
            <div class="form-group">
                <label asp-for="InputModel!.Name" class="control-label"></label>
                <input asp-for="InputModel!.Name" class="form-control" />
                <span asp-validation-for="InputModel!.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InputModel!.Artist" class="control-label"></label>
                @* <select asp-for="InputModel!.Artist" asp-items="@Model.Artists.Select(a => new SelectListItem { Value = a.Id.ToString(), Text = a.Nickname })" class="form-control"></select> *@
                <select asp-for="InputModel!.Artist" asp-items="@Model.Artists.ConstructListItems(a => a.Id.ToString(), a => a.Nickname)" class="form-control"></select>
                <span asp-validation-for="InputModel!.Artist" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InputModel!.Genres" class="control-label"></label>
                <select multiple asp-for="InputModel!.Genres" asp-items="@Model.Genres.Select(a => new SelectListItem { Value = a.Id.ToString(), Text = a.Name })" class="form-control"></select>
                <span asp-validation-for="InputModel!.Genres" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SampleApp1.Web.MVC/Views/Songs/Index.cshtml
@model IEnumerable<SongViewModel>
@{
    ViewData["Title"] = "Songs";
}

<h1>Songs</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Artist)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genres)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var viewModel in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => viewModel.Name)
                </td>
                <td>
                    <a asp-controller="Artists" asp-action="Details" asp-route-id="@viewModel.Artist.Id">@viewModel.Artist.Nickname</a>
                </td>
                <td>
                    @foreach (var genre in viewModel.Genres)
                    {
                        <div>
                            <a asp-controller="Genres" asp-action="Details" asp-route-id="@genre.Id">@genre.Name</a>
                        </div>
                    }
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@viewModel.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@viewModel.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@viewModel.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>